language: node_js

node_js:
 - "node"

install:
 - cd src
 - npm install

script:
 - npm test

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  on: develop
  app: vacancy_backend

notifications:
  slack: $SLACK
