language: node_js

node_js:
 - "node"

install:
 - cd src
 - npm install

script:
 - npm test

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  app:
    develop: vacancy-backend
  run:
    - "cd src"
    - "npm install"
    - "npm run app"

notifications:
  slack: bsi-ifserra:xPzy7oEVH2xDQRP2CZ6WEECm
